let how = document.querySelector('#how');
console.log(how);
let current = document.querySelector('#current');
console.log(current);
let high = document.querySelector('#high');
console.log(high);
let green = document.querySelector('#green');
console.log(green);
let red = document.querySelector('#red');
console.log(red);
let yellow = document.querySelector('#yellow');
console.log(yellow);
let blue = document.querySelector('#blue');
console.log(blue);
let start = document.querySelector('#start');
console.log(start);
let reset = document.querySelector('#reset');
console.log(reset);